name: 3dgs-avatar
channels:
  - pytorch3d
  - pytorch
  - iopath
  - fvcore
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - ffmpeg=4.2.2
  - fvcore=0.1.5
  - iopath=0.1.9
  - plyfile=0.8.1
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.12.1
  - pytorch3d=0.7.1
  - torchaudio=0.12.1
  - torchmetrics=0.11.4
  - torchvision=0.13.1
  - trimesh=3.23.5
  - tqdm
  - pip:
      - submodules/diff-gaussian-rasterization
      - submodules/simple-knn
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - click==8.1.7
      - docker-pycreds==0.4.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - hydra-core==1.3.2
      - imageio==2.31.2
      - importlib-metadata==6.7.0
      - importlib-resources==5.12.0
      - libigl==2.4.1
      - lpips==0.1.4
      - networkx==2.6.3
      - omegaconf==2.3.0
      - opencv-python-headless==4.9.0.80
      - pathtools==0.1.2
      - protobuf==4.24.4
      - psutil==5.9.8
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.13.0
      - pywavelets==1.3.0
      - scikit-image==0.19.3
      - scipy==1.7.3
      - sentry-sdk==2.3.1
      - setproctitle==1.3.3
      - smmap==5.0.1
      - tifffile==2021.11.2
      # - tinycudann==1.7
      - wandb==0.15.11
      - zipp==3.15.0
