# @package _global_

dataset_name: LYH3

dataset:
  name: zjumocap
  root_dir: "./data/ZJUMoCap"
  subject: LYH3
  refine: false

  train_views: [ '1' ]
  val_views: ['1']
  test_views:
    view: ${dataset.val_views}
    video: ['1']
    all: []
  predict_views: ['1']

  train_frames: [30,700, 2]
  val_frames: [ 30,736, 200 ]
  test_frames:
    view: [1,736, 60]
    video: [ 0,736, 90]
    all: [  0,736,90]
  predict_frames: [0,0, 1]

  origin_hw:
    - 1280
    - 1080
    
  img_hw:
    - 1060
    - 900
    
  lanczos: false
  resolution: -1
  white_background: false
  data_device: cuda
  eval: false
  smpl_type: smplx
  # freeview: true