# @package _global_

dataset_name: SC01

dataset:
  name: zjumocap
  root_dir: "./data/ZJUMoCap"
  subject: SC01
  refine: false
  #train_views: [ '59']
  train_views: [ '1', '2', '3', '4', '5', '6', '7', '9', '10', '11', '12', 
                '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23',
                 '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34',
                  '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45',
                   '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56',
                    '57', '58', '59']
  # train_views: [ '1', '3','5', '7', '9','11',
  #               '13', '15', '17',  '19',  '21', '23',
  #                '25', '27', '29', '31', '33', 
  #                 '35','37',  '39',  '41',  '43','45',
  #                  '47', '49', '51','53','55',
  #                   '57', '59']

  val_views: ['19']
  test_views:
    view: ${dataset.val_views}
    video: ['29']
    all: []
  predict_views: ['60']

  train_frames: [0,1280, 12]
  val_frames: [ 900,1280, 100 ]
  test_frames:
    view: [0,1280, 1]
    video: [ 0,1280, 300]
    all: [  0,1280, 300]
  predict_frames: [0,0, 1]

  origin_hw:
    - 4000
    - 3000
    
  img_hw:
    - 2000
    - 1500
    
  lanczos: false
  resolution: -1
  white_background: false
  data_device: cuda
  eval: false
  smpl_type: smplx
  # freeview: true
